name = "stillas"
license = "MIT"
licenselink = "https://github.com/vimux/blank/blob/master/LICENSE.md"
description = "Starter Hugo theme for developers."
homepage = "https://github.com/vimux/blank/"
tags = ["blog", "plain", "blank", "starter"]
features = ["blog"]
min_version = 0.26

[author]
  name = "marcker"
  homepage = "https://github.com/marcker"
