description = "Basic theme for Hugo framework."
homepage = "https://github.com/stillas/theme"
license = "MIT"
licenselink = "https://github.com/stillas/theme/blob/development/license.md"
min_version = 0.26
name = "stillas"
tags = ["blank", "clean", "developer", "empty", "minimal", "minimalist", "simple", "starter", "theme"]

[author]
homepage = "https://github.com/marcker"
name = "marcker"
